### ISSUE TITLE
With 0.1.3 find calls are no longer cached

### ISSUE THREAD

**Issue by sshaw** [orslumen/record-cache#34]
Using 0.1.2 `Model.find` is cached, with 0.1.3 this is no longer the case, one must use

```ruby
Model.where(:id => 1).first
```

**Comment by JohnMorales** [comment]
FYI, #42 now provides failing tests that reproduces this issue and also provides the fixed mentioned above.

**Comment by orslumen** [comment]
Merged PR #42 which should fix the issue.

@JohnMorales: thanks!
