### ISSUE TITLE
Rails 4

### ISSUE THREAD

**Issue by joshdover** [orslumen/record-cache#38]
Do you know how much work for Rails 4 needs to be done for this? I need something like record-cache pretty badly right now and probably have the time to take a crack at it. Pointing me in the right direction could be really helpful.

**Comment by bradw2k** [comment]
@joshdover Any chance you can share a PR or other for version that works for Rails 4.2?  @robinroestenburg Any updates?  Our use case is we have a dozen tables that we just want to fully cache on system startup in Rails 4.2.

**Comment by robinroestenburg** [comment]
@bradw2k Rails 4.0 is working, see my PR #41. I don't think adding 4.1 or 4.2 will be a lot of work. Our Rails 4.2 upgrade was postponed a bit, so I have not had time to work on it. I hope to restart the upgrade work somewhere by the end of this month (May).

**Comment by orslumen** [comment]
rails 4.0 and 4.1 support added, see version 0.1.4
