### ISSUE TITLE
How to expire cache when ActiveRecord::Persistence::reload() or delete() is called?

### ISSUE THREAD

**Issue by hey-jude** [orslumen/record-cache#43]
http://apidock.com/rails/ActiveRecord/Persistence/reload

Current cache is not expired when reload() or delete() is called.

**Comment by orslumen** [comment]
When calling ```delete``` the ActiveRecord callbacks are not triggered, so in most cases you should use ```destroy``` instead. When this is not possible, Record Cache needs to be informed that a particular is invalid:

```
Person.record_cache.invalidate(3)
```

informs Record Cache that the ```Person``` record with id ```3``` should be invalidated from the cache.
